// Base de exames — estrutura idêntica ao medicamentos.js
// Para adicionar um exame: inclua um novo objeto no array seguindo o padrão abaixo.
// Campos obrigatórios: nome, grupo, indicacoes[], preparo[], contraindicacoes[], tempo, obs
const EXAMES_SOLICITADOS = [

  // ── HEMATOLOGIA ─────────────────────────────────────────
  {
    nome: 'Hemograma completo com diferencial',
    grupo: 'Laboratório — Hematologia',
    indicacoes: [
      'Investigação de anemia, leucocitose ou trombocitopenia',
      'Avaliação de infecção ou inflamação aguda',
      'Rastreamento de hemopatias',
      'Pré-operatório de rotina',
    ],
    preparo: [
      'Jejum não obrigatório',
      'Informar medicamentos em uso (anticoagulantes, imunossupressores, quimioterápicos)',
    ],
    contraindicacoes: [],
    tempo: '1 – 4 h',
    obs: 'Inclui eritrograma, leucograma com diferencial e plaquetas.',
  },
  {
    nome: 'Coagulograma (TAP/INR e TTPa)',
    grupo: 'Laboratório — Hematologia',
    indicacoes: [
      'Avaliação de sangramento ou coagulopatia',
      'Monitorização de anticoagulação oral (warfarina)',
      'Pré-operatório de médio e alto risco',
      'Suspeita de disfunção hepática grave',
    ],
    preparo: [
      'Informar uso de anticoagulantes (warfarina, heparina, NOACs)',
      'Coletar preferencialmente antes da dose do anticoagulante',
    ],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'TAP/INR avalia via dependente de vitamina K; TTPa monitora heparina não fracionada.',
  },
  {
    nome: 'Reticulócitos',
    grupo: 'Laboratório — Hematologia',
    indicacoes: [
      'Diferenciação de anemia regenerativa vs hipoplásica',
      'Monitorização de resposta a ferro, B12 ou eritropoetina',
      'Pós-transplante de medula óssea',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: '',
  },
  {
    nome: 'Tipagem sanguínea ABO/Rh + PAI',
    grupo: 'Laboratório — Hematologia',
    indicacoes: [
      'Pré-transfusão (obrigatório)',
      'Pré-operatório com potencial de sangramento',
      'Gestante — rastreamento de isoimunização Rh',
      'Paciente politransfundido',
    ],
    preparo: [
      'Identificar o paciente com pulseira e conferir nome antes da coleta',
      'ATENÇÃO: erro de identificação pode causar reação transfusional fatal',
    ],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: 'PAI (Pesquisa de Anticorpos Irregulares / Coombs indireto) obrigatória em gestantes e politransfundidos.',
  },


  // ── BIOQUÍMICA ───────────────────────────────────────────
  {
    nome: 'Glicemia em jejum',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Diagnóstico e monitorização de diabetes mellitus',
      'Investigação de hipoglicemia',
      'Avaliação metabólica geral e pré-operatória',
    ],
    preparo: [
      'Jejum mínimo de 8 h (água sem açúcar é permitida)',
      'Informar uso de hipoglicemiantes orais e insulina',
    ],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: 'Glicemia ≥ 126 mg/dL em jejum em 2 ocasiões confirma DM2.',
  },
  {
    nome: 'Ureia e Creatinina',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Avaliação de função renal',
      'Suspeita de IRA ou DRC',
      'Monitorização em uso de nefrotóxicos (AINEs, aminoglicosídeos, contraste)',
      'Pré-contraste iodado para TC',
    ],
    preparo: [
      'Jejum não obrigatório',
      'Informar uso de IECA, ARA-II, AINEs e creatina',
    ],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Calcular TFG estimada (CKD-EPI) com creatinina sérica, idade e sexo.',
  },
  {
    nome: 'Eletrólitos (Na⁺, K⁺, Cl⁻)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Distúrbios hidroeletrolíticos (hipo/hipernatremia, hipo/hipercalemia)',
      'Insuficiência renal, diarreia intensa ou vômitos',
      'Uso de diuréticos',
      'Monitorização em UTI',
    ],
    preparo: [
      'Jejum não obrigatório',
      'Evitar estase prolongada com o garrote (pode causar pseudo-hipercalemia por hemólise)',
    ],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: '',
  },
  {
    nome: 'Cálcio total e iônico',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Tetania, espasmos musculares, parestesias',
      'Suspeita de hipo ou hiperparatiroidismo',
      'Hipercalcemia de malignidade',
      'Monitorização em UTI',
    ],
    preparo: [
      'Jejum de 4 h para cálcio total',
      'Cálcio iônico: não requer jejum; evitar contaminação com EDTA',
    ],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Correção: Ca corrigido = Ca total + 0,8 × (4 − albumina sérica).',
  },
  {
    nome: 'Magnésio sérico',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Tetania, arritmias cardíacas, convulsões',
      'Monitorização de reposição de magnésio',
      'Alcoolismo crônico e má-absorção',
      'Uso de diuréticos de alça ou tiazídicos',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: '',
  },
  {
    nome: 'Ácido úrico sérico',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Investigação de gota aguda ou crônica',
      'Síndrome metabólica',
      'Monitorização de alopurinol',
      'Síndrome de lise tumoral',
    ],
    preparo: [
      'Jejum de 4 h',
      'Evitar álcool e dieta hiperpurínica nas 24 h anteriores',
    ],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: '',
  },
  {
    nome: 'Albumina sérica',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Avaliação nutricional e estado inflamatório crônico',
      'Monitorização em hepatopatia crônica',
      'Síndrome nefrótica',
      'Interpretação do cálcio total',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Reagente de fase aguda negativa — valores baixos em inflamação aguda não significam necessariamente desnutrição.',
  },
  {
    nome: 'Lactato sérico',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Suspeita de sepse grave ou choque séptico',
      'Avaliação de hipóxia tecidual',
      'Intoxicação por metformina ou cianeto',
      'Monitorização de ressuscitação volêmica',
    ],
    preparo: [
      'Coletar em tubo fluoretado ou em gelo seco',
      'Processar em < 15 min (metabolismo celular altera o resultado)',
    ],
    contraindicacoes: [],
    tempo: '< 1 h (urgência)',
    obs: 'Lactato ≥ 2 mmol/L indica hipoperfusão; ≥ 4 mmol/L define choque séptico (Sepsis-3).',
  },
  {
    nome: 'Hemoglobina glicada (HbA1c)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Diagnóstico de diabetes mellitus',
      'Monitoramento do controle glicêmico nos últimos 2 a 3 meses',
      'Ajuste terapêutico em pacientes diabéticos',
    ],
    preparo: ['Jejum não obrigatório', 'Informar presença de hemoglobinopatias ou anemia hemolítica'],
    contraindicacoes: [],
    tempo: '4 – 12 h',
    obs: 'HbA1c ≥ 6,5% confirma diagnóstico de DM2. Pode ser subestimada em anemia hemolítica ou hemoglobinopatias.',
  },
  {
    nome: 'Perfil Lipídico (Colesterol total, HDL, LDL, Triglicerídeos)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Rastreamento de dislipidemia e risco cardiovascular',
      'Monitoramento de terapia com estatinas ou fibratos',
      'Avaliação metabólica em obesidade, DM2 ou síndrome metabólica',
    ],
    preparo: ['Jejum de 10 a 12 horas para perfil completo', 'Evitar álcool e refeições gordurosas 24h antes'],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'LDL calculado pela fórmula de Friedewald é inválido se triglicerídeos > 400 mg/dL.',
  },
  {
    nome: 'Proteína C Reativa (PCR)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Detecção e monitoramento de processos inflamatórios ou infecciosos agudos',
      'Avaliação de atividade em doenças reumatológicas',
      'Estratificação de risco cardiovascular com PCR ultrassensível',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: 'PCR padrão eleva-se em inflamação e infecção; PCR ultrassensível é usada para risco cardiovascular.',
  },
  {
    nome: 'Hormônio Tireoestimulante (TSH)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Rastreamento e diagnóstico de hipotireoidismo e hipertireoidismo',
      'Monitoramento de reposição com levotiroxina',
      'Investigação de dislipidemia, infertilidade ou fadiga crônica',
    ],
    preparo: ['Jejum não obrigatório', 'Coletar preferencialmente pela manhã devido à variação circadiana'],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'Alterações do TSH precedem as de T4 livre; é o teste de escolha para triagem tireoidiana.',
  },
  {
    nome: 'T4 Livre (T4L)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Confirmação diagnóstica de disfunção tireoidiana após TSH alterado',
      'Monitoramento de tratamento do hipertireoidismo',
      'Avaliação de tireoidite subclínica',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'Não sofre interferência significativa de proteínas carreadoras; útil em gestantes e uso de anticoncepcionais.',
  },
  {
    nome: 'Fosfatase Alcalina (FA)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Investigação de colestase hepática ou obstrução biliar',
      'Avaliação de doenças ósseas com aumento da atividade osteoblástica (Paget, metástases)',
      'Monitoramento de hepatotoxicidade medicamentosa',
    ],
    preparo: ['Jejum de 4 horas recomendado'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Elevações fisiológicas ocorrem na gestação, crescimento infantil e adolescência.',
  },
  {
    nome: 'Gama-Glutamil Transferase (GGT)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Confirmação de origem hepática da elevação de fosfatase alcalina',
      'Marcador sensível de uso crônico de álcool',
      'Investigação de colestase intra ou extra-hepática',
    ],
    preparo: ['Jejum não obrigatório', 'Evitar álcool 24h antes do exame'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Pode elevar-se isoladamente em uso de fenitoína, fenobarbital ou esteatose hepática.',
  },
  {
    nome: 'Bilirrubinas Totais e Frações (Direta e Indireta)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Investigação de icterícia',
      'Diagnóstico diferencial de anemias hemolíticas',
      'Avaliação de função hepática excretora e colestase',
      'Rastreamento neonatal de hiperbilirrubinemia',
    ],
    preparo: ['Jejum de 4 horas', 'Proteger amostra da luz para evitar degradação da bilirrubina'],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: 'Hiperbilirrubinemia indireta sugere hemólise ou síndrome de Gilbert; direta sugere colestase ou lesão hepatocelular.',
  },
  {
    nome: 'Transaminases (TGO/AST e TGP/ALT)',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Rastreamento e monitoramento de lesão hepatocelular',
      'Investigação de hepatites virais, medicamentosas ou alcoólicas',
      'Avaliação de esteatose hepática e cirrose',
      'Check-up metabólico geral',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: 'Relação TGO/TGP > 2 sugere etiologia alcoólica; TGP mais específica para lesão hepática.',
  },
  {
    nome: 'Amilase e Lipase',
    grupo: 'Laboratório — Bioquímica',
    indicacoes: [
      'Diagnóstico de pancreatite aguda',
      'Investigação de dor abdominal alta de causa obscura',
      'Monitoramento de complicações pós-CPRE ou trauma pancreático',
    ],
    preparo: ['Jejum não obrigatório', 'Evitar opioides antes da coleta quando possível'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Lipase é mais sensível e específica que amilase para pancreatite aguda, especialmente em apresentação tardia.',
  },

  // ── FUNÇÃO HEPÁTICA ─────────────────────────────────────
  {
    nome: 'TGO (AST) e TGP (ALT)',
    grupo: 'Laboratório — Função Hepática',
    indicacoes: [
      'Hepatite aguda ou crônica',
      'Hepatotoxicidade medicamentosa (estatinas, antituberculosos)',
      'Cirrose e suas complicações',
      'Avaliação pré-operatória',
    ],
    preparo: [
      'Jejum de 4 h',
      'Evitar atividade física intensa nas 24 h anteriores (AST se eleva em lesão muscular)',
    ],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'ALT é mais específica para fígado. AST também sobe em IAM e rabdomiólise.',
  },
  {
    nome: 'Gama-GT e Fosfatase Alcalina',
    grupo: 'Laboratório — Função Hepática',
    indicacoes: [
      'Doença colestática (coledocolitíase, colangite)',
      'Abuso de álcool (GGT muito sensível)',
      'Metástases hepáticas',
      'Doença óssea — FA de origem óssea',
    ],
    preparo: ['Jejum de 4 h'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'FA elevada com GGT normal sugere origem óssea (Paget, metástase óssea).',
  },
  {
    nome: 'Bilirrubinas total e frações',
    grupo: 'Laboratório — Função Hepática',
    indicacoes: [
      'Icterícia (diagnóstico e monitorização)',
      'Hepatite e colestase',
      'Anemia hemolítica (BI elevada)',
      'Doença de Gilbert',
    ],
    preparo: [
      'Jejum de 4 h',
      'Proteger a amostra da luz (fotodegradação)',
    ],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'BD predominante → colestase ou hepatocelular. BI predominante → hemólise ou Gilbert.',
  },
  {
    nome: 'Lipase e Amilase',
    grupo: 'Laboratório — Função Hepática',
    indicacoes: [
      'Suspeita de pancreatite aguda',
      'Dor abdominal epigástrica com irradiação dorsal',
      'Monitorização de pancreatite em evolução',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Lipase tem maior especificidade pancreática. Amilase também sobe em parotidite e insuficiência renal.',
  },

  // ── INFLAMATÓRIOS E INFECCIOSOS ──────────────────────────
  {
    nome: 'PCR quantitativa (Proteína C-Reativa)',
    grupo: 'Laboratório — Inflamatórios e Infecciosos',
    indicacoes: [
      'Diferenciação de infecção bacteriana vs viral',
      'Monitorização de inflamação e resposta ao antibiótico',
      'Doenças autoimunes (artrite reumatoide, LES)',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 4 h',
    obs: 'PCR > 100 mg/L sugere infecção bacteriana grave. Sobe em 6 h, pico em 48 h.',
  },
  {
    nome: 'Procalcitonina (PCT)',
    grupo: 'Laboratório — Inflamatórios e Infecciosos',
    indicacoes: [
      'Diagnóstico de sepse bacteriana',
      'Guia de início e suspensão de antibioticoterapia',
      'Diferenciação de pneumonia bacteriana vs viral',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 4 h',
    obs: 'PCT > 0,5 ng/mL: infecção bacteriana provável. > 2: sepse. > 10: choque séptico.',
  },
  {
    nome: 'VHS (Velocidade de Hemossedimentação)',
    grupo: 'Laboratório — Inflamatórios e Infecciosos',
    indicacoes: [
      'Doenças inflamatórias crônicas (AR, LES, arterite de células gigantes)',
      'Tuberculose',
      'Mieloma múltiplo',
      'Monitorização de atividade inflamatória a longo prazo',
    ],
    preparo: [
      'Jejum não obrigatório',
      'Coletar em tubo com EDTA e processar em < 4 h',
    ],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: 'Sobe lentamente (dias) — pouco útil em urgência. Normal: ♂ < 15 mm/h; ♀ < 20 mm/h.',
  },
  {
    nome: 'Hemocultura (2 amostras de sítios diferentes)',
    grupo: 'Laboratório — Inflamatórios e Infecciosos',
    indicacoes: [
      'Febre sem foco definido',
      'Suspeita de bacteremia ou sepse',
      'Endocardite infecciosa',
      'Paciente com cateter central e febre',
    ],
    preparo: [
      'Coletar ANTES do antibiótico sempre que possível',
      'Anti-sepsia rigorosa: álcool 70% + clorexidina alcoólica',
      'Coletar 2 pares (aeróbio + anaeróbio) de sítios venosos diferentes, intervalo 15–30 min',
      'Volume mínimo 10 mL por frasco em adultos',
      'NUNCA coletar pelo cateter venoso central',
    ],
    contraindicacoes: [],
    tempo: '24 h – 5 dias (crescimento automático)',
    obs: 'Identificar horário e sítio da coleta nos frascos.',
  },
  {
    nome: 'Urocultura com antibiograma',
    grupo: 'Laboratório — Inflamatórios e Infecciosos',
    indicacoes: [
      'ITU complicada ou de repetição',
      'Pielonefrite',
      'Sepse de foco urinário',
      'Avaliação pré-procedimento urológico',
    ],
    preparo: [
      'Higienizar genitália antes da coleta',
      'Desprezar o primeiro jato — coletar jato médio em frasco estéril',
      'Processar em < 2 h ou refrigerar a 4 °C por até 24 h',
    ],
    contraindicacoes: [],
    tempo: '24 – 72 h',
    obs: '> 10⁵ UFC/mL = bacteriúria significativa. Sempre solicitar com antibiograma.',
  },
  {
    nome: 'Cultura de secreção com antibiograma',
    grupo: 'Laboratório — Inflamatórios e Infecciosos',
    indicacoes: [
      'Ferida operatória infectada',
      'Úlcera de pressão com sinais de infecção',
      'Abscesso drenado',
      'Pneumonia aspirativa (aspirado traqueal)',
    ],
    preparo: [
      'Coletar de tecido profundo — swab superficial tem alta taxa de contaminação',
      'Coletar antes de iniciar ou trocar antibiótico',
      'Encaminhar ao laboratório imediatamente',
      'Identificar o sítio da coleta na requisição',
    ],
    contraindicacoes: [],
    tempo: '24 – 72 h',
    obs: 'Qualidade da coleta determina confiabilidade do resultado.',
  },

  // ── CARDÍACO ─────────────────────────────────────────────
  {
    nome: 'Troponina I de alta sensibilidade (seriada)',
    grupo: 'Laboratório — Cardíaco',
    indicacoes: [
      'Síndrome coronariana aguda (SCA)',
      'Dor torácica de investigação',
      'Miocardite',
      'TEP grave com disfunção ventricular direita',
    ],
    preparo: [
      'Coleta inicial + repetir em 3 h (protocolo 0/3 h) ou 1 h (hs-TnI)',
      'Informar hora exata do início dos sintomas na requisição',
    ],
    contraindicacoes: [],
    tempo: '< 1 h (urgência)',
    obs: 'Elevação modesta ocorre em IC descompensada, sepse, TEP e IRC — interpretar no contexto clínico.',
  },
  {
    nome: 'CK total e CK-MB massa',
    grupo: 'Laboratório — Cardíaco',
    indicacoes: [
      'Suspeita de IAM (complementar à troponina)',
      'Rabdomiólise',
      'Miopatias inflamatórias',
      'Monitorização de estatinas em pacientes sintomáticos',
    ],
    preparo: [
      'Evitar atividade física intensa nas 24 h anteriores (eleva CK total)',
    ],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'CK-MB massa > 5 ng/mL ou > 3–6% da CK total sugere lesão miocárdica.',
  },
  {
    nome: 'BNP ou NT-proBNP',
    grupo: 'Laboratório — Cardíaco',
    indicacoes: [
      'Dispneia de investigação (IC vs pulmonar)',
      'Diagnóstico e estratificação de gravidade de IC',
      'Monitorização de tratamento da IC',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'BNP > 100 pg/mL ou NT-proBNP > 300 pg/mL sugere IC. Sobe com a idade e na IRC.',
  },
  {
    nome: 'D-dímero',
    grupo: 'Laboratório — Cardíaco',
    indicacoes: [
      'Exclusão de TEP em baixa probabilidade clínica (Wells)',
      'Exclusão de TVP em baixa probabilidade clínica',
      'CIVD',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: 'Alto VPN. Não específico — sobe em infecção, gravidez, cirurgia e idosos. NÃO confirma TEP/TVP.',
  },

  // ── CARDIOPULMONAR ───────────────────────────────────────
  {
    nome: 'Gasometria arterial',
    grupo: 'Laboratório — Cardiopulmonar',
    indicacoes: [
      'Insuficiência respiratória aguda',
      'Distúrbio ácido-base',
      'Hipoxemia',
      'Monitorização de ventilação mecânica',
      'Intoxicações (CO, metanol, metformina)',
    ],
    preparo: [
      'Punção arterial — artéria radial preferencial',
      'Realizar teste de Allen antes da punção radial',
      'Comprimir o sítio por mínimo 5 min pós-coleta',
      'Processar imediatamente ou em gelo em < 15 min',
      'Informar FiO₂ ou fluxo de O₂ (L/min) na requisição',
    ],
    contraindicacoes: [
      'Teste de Allen negativo (contra punção radial — usar sítio alternativo)',
      'Coagulopatia grave (relativa)',
      'Fístula arteriovenosa ipsilateral',
    ],
    tempo: '< 30 min (urgência)',
    obs: 'Coletar em seringa heparinizada. Bolhas de ar e atraso no processamento alteram PaO₂ e PaCO₂.',
  },

  // ── HORMÔNIOS ────────────────────────────────────────────
  {
    nome: 'TSH e T4 livre',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Suspeita de hipo ou hipertireoidismo',
      'Monitorização de reposição de levotiroxina',
      'Rastreamento em gestantes, idosos e pacientes psiquiátricos',
      'Nódulo tireoidiano',
    ],
    preparo: [
      'Jejum não obrigatório',
      'Coleta preferencialmente pela manhã, antes de tomar levotiroxina se em uso',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'TSH é o exame de triagem mais sensível. T4 livre confirma o diagnóstico funcional.',
  },
  {
    nome: 'β-hCG quantitativo',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Confirmação de gravidez',
      'Dor pélvica em mulher em idade fértil (excluir gravidez ectópica)',
      'Monitorização pós-abortamento ou pós-doença trofoblástica',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '1 – 3 h',
    obs: 'Positivo a partir de 25 mIU/mL. Duplica a cada 48 h no 1º trimestre normal.',
  },
  {
    nome: 'Cortisol sérico matinal',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Suspeita de insuficiência adrenal (doença de Addison)',
      'Rastreamento de síndrome de Cushing',
      'Avaliação de fadiga crônica e hipotensão inexplicada',
    ],
    preparo: [
      'Coletar entre 7h e 9h da manhã devido ao ritmo circadiano',
      'Informar uso de corticosteroides orais, tópicos ou inalatórios',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'Valor matinal baixo sugere insuficiência adrenal; valor elevado isoladamente não confirma Cushing.',
  },
  {
    nome: 'Prolactina sérica',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Investigação de galactorreia não puerperal',
      'Amenorreia ou oligomenorreia',
      'Infertilidade feminina e masculina',
      'Suspeita de adenoma hipofisário secretor',
    ],
    preparo: [
      'Coletar pela manhã em repouso de 30 minutos',
      'Evitar estresse, exercício físico intenso e estimulação mamária 12h antes',
      'Jejum não obrigatório',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'Valores elevados exigem exclusão de macroprolactinemia; medicamentos como antipsicóticos e metoclopramida elevam prolactina.',
  },
  {
    nome: 'Testosterona total e livre',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Investigação de hipogonadismo masculino',
      'Disfunção erétil e redução da libido',
      'Infertilidade masculina',
      'Avaliação de síndrome dos ovários policísticos em mulheres',
    ],
    preparo: [
      'Coletar pela manhã entre 7h e 10h',
      'Jejum não obrigatório',
    ],
    contraindicacoes: [],
    tempo: '4 – 24 h',
    obs: 'Níveis diminuem com idade, obesidade e uso de opioides ou glicocorticoides.',
  },
  {
    nome: 'Estradiol (E2)',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Avaliação da reserva ovariana e função folicular',
      'Monitoramento de indução da ovulação em reprodução assistida',
      'Investigação de puberdade precoce ou tardia',
      'Avaliação de amenorreia e menopausa',
    ],
    preparo: [
      'Em mulheres com ciclos menstruais, coletar conforme fase do ciclo',
      'Jejum não obrigatório',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'Interpretação depende da fase do ciclo menstrual e idade da paciente.',
  },
  {
    nome: 'Hormônio Folículo-Estimulante (FSH)',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Avaliação da reserva ovariana e falência ovariana prematura',
      'Investigação de infertilidade feminina e masculina',
      'Diagnóstico de menopausa',
      'Avaliação de puberdade precoce ou tardia',
    ],
    preparo: [
      'Em mulheres com ciclos, coletar no 2º ao 5º dia do ciclo menstrual',
      'Jejum não obrigatório',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'FSH elevado na mulher sugere baixa reserva ovariana ou menopausa; no homem, indica falência testicular primária.',
  },
  {
    nome: 'Hormônio Luteinizante (LH)',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Investigação de distúrbios menstruais e anovulação',
      'Predição do pico ovulatório em reprodução assistida',
      'Diagnóstico de síndrome dos ovários policísticos',
      'Avaliação de hipogonadismo hipogonadotrófico',
    ],
    preparo: [
      'Em mulheres com ciclos, coletar no 2º ao 5º dia ou conforme orientação',
      'Jejum não obrigatório',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'Relação LH/FSH > 2 é critério sugestivo de SOP; LH baixo com FSH baixo sugere causa central.',
  },
  {
    nome: 'Progesterona',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Confirmação de ovulação em ciclos menstruais',
      'Avaliação de insuficiência lútea em infertilidade',
      'Monitoramento de gestação inicial de risco',
      'Investigação de sangramento uterino anormal',
    ],
    preparo: [
      'Coletar no 21º dia de ciclo menstrual regular de 28 dias',
      'Jejum não obrigatório',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'Valores acima de 10 ng/mL na fase lútea média confirmam ovulação adequada.',
  },
  {
    nome: 'Paratormônio (PTH)',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Diagnóstico diferencial de hipercalcemia e hipocalcemia',
      'Avaliação de hiperparatireoidismo primário ou secundário',
      'Monitoramento em doença renal crônica',
      'Investigação de osteoporose e litíase renal recorrente',
    ],
    preparo: [
      'Coletar em jejum de 8 horas pela manhã',
      'Dosar cálcio total e albumina simultaneamente',
    ],
    contraindicacoes: [],
    tempo: '4 – 12 h',
    obs: 'PTH elevado com cálcio alto sugere hiperparatireoidismo primário; com cálcio baixo sugere secundário.',
  },
  {
    nome: '25-Hidroxivitamina D (Vitamina D)',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Rastreamento de hipovitaminose D',
      'Avaliação de osteoporose, osteomalácia e risco de fraturas',
      'Monitoramento de suplementação',
      'Doenças autoimunes e distúrbios de absorção intestinal',
    ],
    preparo: ['Jejum não obrigatório'],
    contraindicacoes: [],
    tempo: '24 – 72 h',
    obs: 'Melhor marcador dos estoques corporais de vitamina D; valores desejáveis acima de 30 ng/mL.',
  },
  {
    nome: 'Insulina sérica e HOMA-IR',
    grupo: 'Laboratório — Hormônios',
    indicacoes: [
      'Avaliação de resistência à insulina em obesidade e SOP',
      'Diagnóstico de síndrome metabólica',
      'Investigação de hipoglicemia hiperinsulinêmica',
      'Monitoramento em pré-diabetes',
    ],
    preparo: [
      'Jejum de 8 a 12 horas',
      'Coletar glicemia de jejum simultaneamente para cálculo do HOMA-IR',
    ],
    contraindicacoes: [],
    tempo: '2 – 6 h',
    obs: 'HOMA-IR = insulina jejum × glicemia jejum / 22,5; valores > 2,7 sugerem resistência à insulina.',
  },

  // ── URINA E FEZES ────────────────────────────────────────
  {
    nome: 'Urina tipo 1 (EAS)',
    grupo: 'Laboratório — Urina e Fezes',
    indicacoes: [
      'Rastreamento de ITU',
      'Investigação de hematúria ou proteinúria',
      'Avaliação renal e metabólica geral',
      'Pré-operatório',
    ],
    preparo: [
      'Higienizar genitália antes da coleta',
      'Desprezar o primeiro jato — coletar jato médio em frasco estéril',
      'Processar em < 2 h',
    ],
    contraindicacoes: [],
    tempo: '1 – 2 h',
    obs: '> 5 leucócitos/campo sugere ITU. Nitrito positivo tem alta especificidade para gram-negativos.',
  },
  {
    nome: 'Sumário de fezes com pesquisa de parasitas',
    grupo: 'Laboratório — Urina e Fezes',
    indicacoes: [
      'Diarreia crônica de investigação',
      'Suspeita de parasitoses intestinais',
      'Anemia ferropriva sem causa evidente',
      'Eosinofilia periférica',
    ],
    preparo: [
      'Coletar em frasco limpo e seco (não estéril)',
      'Evitar contaminação com urina ou água sanitária',
      'Coletar 3 amostras em dias alternados para maior sensibilidade',
      'Refrigerar se não processar imediatamente',
    ],
    contraindicacoes: [],
    tempo: '24 – 48 h',
    obs: 'Método de Hoffman (sedimentação espontânea) é o padrão no SUS.',
  },

  // ── RADIOGRAFIA ──────────────────────────────────────────
  {
    nome: 'Raio-X de Tórax PA e Perfil',
    grupo: 'Imagem — Radiografia',
    indicacoes: [
      'Pneumonia, derrame pleural, pneumotórax',
      'Cardiomegalia e congestão pulmonar',
      'Tuberculose',
      'Avaliação pré-operatória',
      'Monitorização de drenos e cateteres',
    ],
    preparo: [
      'Retirar adornos metálicos do tórax (correntes, brincos)',
      'Realizar em inspiração profunda',
    ],
    contraindicacoes: [
      'Gravidez (relativa — blindar abdome se exame imprescindível)',
    ],
    tempo: 'Imediato',
    obs: 'Solicitar PA em ortostase sempre que possível. Perfil auxilia na localização de lesões.',
  },
  {
    nome: 'Raio-X de Abdome (ortostase e decúbito)',
    grupo: 'Imagem — Radiografia',
    indicacoes: [
      'Suspeita de obstrução intestinal ou íleo paralítico',
      'Pneumoperitônio',
      'Cólica renal (cálculo radioopaco)',
      'Corpo estranho abdominal',
    ],
    preparo: ['Retirar adornos metálicos da região abdominal'],
    contraindicacoes: ['Gravidez (relativa)'],
    tempo: 'Imediato',
    obs: 'Ortostase evidencia níveis hidroaéreos e pneumoperitônio sub-diafragmático.',
  },
  {
    nome: 'Raio-X de Coluna Cervical AP e Lateral',
    grupo: 'Imagem — Radiografia',
    indicacoes: [
      'Trauma cervical',
      'Cervicalgia de investigação',
      'Suspeita de luxação ou fratura cervical',
    ],
    preparo: ['Retirar adornos metálicos do pescoço'],
    contraindicacoes: ['Gravidez (relativa)'],
    tempo: 'Imediato',
    obs: 'Lateral deve incluir C7–T1. TC cervical com reconstrução 3D é superior para traumas graves.',
  },
  {
    nome: 'Raio-X de Coluna Lombar AP e Lateral',
    grupo: 'Imagem — Radiografia',
    indicacoes: [
      'Lombalgia crônica',
      'Fratura por compressão vertebral (osteoporose)',
      'Espondiloartropatia',
      'Escoliose',
    ],
    preparo: ['Retirar adornos metálicos da região lombar'],
    contraindicacoes: ['Gravidez (relativa)'],
    tempo: 'Imediato',
    obs: 'RM lombar é superior para hérnias discais e comprometimento de raízes nervosas.',
  },
  {
    nome: 'Raio-X de Bacia AP',
    grupo: 'Imagem — Radiografia',
    indicacoes: [
      'Trauma de quadril e pelve',
      'Suspeita de fratura do colo femoral',
      'Coxartrose',
      'Avaliação de prótese de quadril',
    ],
    preparo: ['Retirar adornos metálicos pélvicos'],
    contraindicacoes: ['Gravidez (relativa)'],
    tempo: 'Imediato',
    obs: '',
  },
  {
    nome: 'Raio-X de Crânio AP e Lateral',
    grupo: 'Imagem — Radiografia',
    indicacoes: [
      'Investigação de fratura craniana pós-trauma (quando TC não disponível)',
      'Triagem de corpo estranho metálico antes de RM',
    ],
    preparo: ['Retirar adornos metálicos da cabeça e pescoço'],
    contraindicacoes: ['Gravidez (relativa)'],
    tempo: 'Imediato',
    obs: 'TC de crânio é o exame de escolha para trauma. Rx de crânio tem indicações muito limitadas.',
  },

  // ── ULTRASSONOGRAFIA ─────────────────────────────────────
  {
    nome: 'Ultrassonografia de Abdome Total',
    grupo: 'Imagem — Ultrassonografia',
    indicacoes: [
      'Dor abdominal inespecífica',
      'Cólica biliar e colelitíase',
      'Hepatomegalia ou esplenomegalia',
      'Ascite',
      'Rastreamento de aneurisma de aorta abdominal',
      'Nódulo hepático ou renal',
    ],
    preparo: [
      'Jejum mínimo de 6 h para adequada visualização da vesícula',
      'Bexiga semi-cheia para complementar avaliação pélvica',
    ],
    contraindicacoes: [],
    tempo: '20 – 40 min',
    obs: 'Exame operador-dependente. Gases intestinais e obesidade podem limitar a visualização.',
  },
  {
    nome: 'Ultrassonografia Pélvica (transvaginal / transabdominal)',
    grupo: 'Imagem — Ultrassonografia',
    indicacoes: [
      'Dor pélvica em mulher',
      'Sangramento uterino anormal',
      'Suspeita de gravidez ectópica',
      'Cistos ovarianos e miomas uterinos',
      'Avaliação de endométrio',
    ],
    preparo: [
      'Via transvaginal: bexiga vazia',
      'Via transabdominal: bexiga cheia (500 mL de água 1 h antes)',
      'Orientar a paciente sobre o procedimento e obter consentimento verbal',
    ],
    contraindicacoes: [
      'Via transvaginal contraindicada em virgens — usar via transabdominal',
      'Estenose vaginal grave',
    ],
    tempo: '20 – 30 min',
    obs: 'Via transvaginal tem maior resolução. Especificar a via na solicitação.',
  },
  {
    nome: 'Ultrassonografia de Vias Urinárias (rins e bexiga)',
    grupo: 'Imagem — Ultrassonografia',
    indicacoes: [
      'Cólica renal e suspeita de cálculo urinário',
      'Hematúria',
      'Hidronefrose',
      'ITU de repetição',
      'Avaliação de massa renal',
    ],
    preparo: ['Bexiga cheia (ingerir 500 mL de água 1 h antes)'],
    contraindicacoes: [],
    tempo: '20 – 30 min',
    obs: '',
  },
  {
    nome: 'Ultrassonografia Doppler de MMII (pesquisa de TVP)',
    grupo: 'Imagem — Ultrassonografia',
    indicacoes: [
      'Suspeita de trombose venosa profunda (TVP)',
      'Edema assimétrico de membros inferiores',
      'Eritema e dor em trajeto venoso',
      'Investigação de TEP com suspeita de TVP proximal',
    ],
    preparo: [
      'Jejum não necessário',
      'Membro em posição anatômica durante o exame',
    ],
    contraindicacoes: [],
    tempo: '30 – 60 min',
    obs: 'Compressibilidade venosa ausente = TVP. Exame de escolha para TVP proximal de MMII.',
  },
  {
    nome: 'Ultrassonografia de Tireoide',
    grupo: 'Imagem — Ultrassonografia',
    indicacoes: [
      'Nódulo tireoidiano palpável ou achado incidental',
      'Bócio',
      'Tireoidite',
      'Guia para PAAF de tireoide',
    ],
    preparo: ['Jejum não necessário'],
    contraindicacoes: [],
    tempo: '20 – 30 min',
    obs: 'Classificação TI-RADS orienta risco de malignidade e indicação de PAAF.',
  },
  {
    nome: 'FAST (Ultrassom à beira-leito — trauma)',
    grupo: 'Imagem — Ultrassonografia',
    indicacoes: [
      'Trauma abdominal com instabilidade hemodinâmica',
      'Suspeita de hemoperitônio ou hemopericárdio',
      'Politraumatismo — rastreamento rápido',
    ],
    preparo: ['Exame de urgência — sem preparo prévio'],
    contraindicacoes: [],
    tempo: '3 – 5 min (urgência)',
    obs: 'Exame de triagem — resultado negativo não exclui lesão. TC confirmatória quando paciente estabilizar.',
  },

  // ── TOMOGRAFIA COMPUTADORIZADA ───────────────────────────
  {
    nome: 'TC de Crânio sem contraste',
    grupo: 'Imagem — Tomografia Computadorizada',
    indicacoes: [
      'Trauma cranioencefálico',
      'AVC isquêmico ou hemorrágico',
      'Hemorragia subaracnóidea',
      'Cefaleia em trovoada',
      'Rebaixamento do nível de consciência',
      'Crise convulsiva inaugural',
    ],
    preparo: [
      'Retirar adornos metálicos da cabeça',
      'Não requer jejum',
    ],
    contraindicacoes: ['Gravidez (relativa — blindar abdome)'],
    tempo: '15 – 30 min',
    obs: 'Exame de escolha para hemorragia aguda. Isquemia < 6 h pode não ser visível — considerar RM DWI.',
  },
  {
    nome: 'TC de Crânio com contraste',
    grupo: 'Imagem — Tomografia Computadorizada',
    indicacoes: [
      'Abscesso cerebral',
      'Neoplasia intracraniana',
      'Meningite com suspeita de complicação',
      'Trombose de seio venoso dural (angio-TC)',
    ],
    preparo: [
      'Jejum de 4 h',
      'Verificar creatinina e histórico de alergia ao contraste iodado',
      'Acesso venoso calibroso (≥ 20G)',
      'Hidratação pré e pós em pacientes de risco nefrotóxico',
    ],
    contraindicacoes: [
      'Alergia grave ao contraste iodado (relativa — pré-medicação possível)',
      'IRC grave (TFG < 30 mL/min/1,73 m²)',
      'Gravidez (relativa)',
    ],
    tempo: '20 – 40 min',
    obs: 'Informar uso de metformina — suspender 48 h pós-contraste em IRC.',
  },
  {
    nome: 'TC de Tórax sem contraste',
    grupo: 'Imagem — Tomografia Computadorizada',
    indicacoes: [
      'Pneumonia de difícil avaliação ou complicada',
      'COVID-19 grave',
      'Suspeita de neoplasia pulmonar',
      'Enfisema pulmonar grave (DPOC)',
      'Nódulo pulmonar',
    ],
    preparo: [
      'Retirar adornos metálicos do tórax',
      'Não requer jejum',
    ],
    contraindicacoes: ['Gravidez (relativa)'],
    tempo: '15 – 30 min',
    obs: '',
  },
  {
    nome: 'TC de Abdome e Pelve com contraste',
    grupo: 'Imagem — Tomografia Computadorizada',
    indicacoes: [
      'Dor abdominal aguda sem diagnóstico',
      'Apendicite aguda',
      'Abscesso intra-abdominal',
      'Neoplasia abdominal ou pélvica',
      'Trauma abdominal',
      'Pancreatite complicada',
      'Obstrução intestinal',
    ],
    preparo: [
      'Jejum de 4 h',
      'Verificar creatinina e histórico de alergia ao contraste iodado',
      'Acesso venoso calibroso',
    ],
    contraindicacoes: [
      'Alergia grave ao contraste iodado',
      'IRC grave (TFG < 30 mL/min/1,73 m²)',
      'Gravidez (relativa)',
    ],
    tempo: '20 – 40 min',
    obs: 'Contraste oral pode ser solicitado junto para melhor delimitação de alças intestinais.',
  },
  {
    nome: 'Angio-TC de Tórax — Protocolo TEP',
    grupo: 'Imagem — Tomografia Computadorizada',
    indicacoes: [
      'Suspeita de tromboembolismo pulmonar (TEP)',
      'Hemoptise sem causa definida',
      'Malformação arteriovenosa pulmonar',
    ],
    preparo: [
      'Jejum de 4 h',
      'Verificar creatinina e histórico de alergia ao contraste',
      'Acesso venoso MSE calibroso (≥ 18G, preferencialmente antecubital)',
      'Paciente deve conseguir apneia de 5–10 s durante a aquisição',
    ],
    contraindicacoes: [
      'Alergia grave ao contraste iodado',
      'IRC grave (TFG < 30)',
      'Gravidez (relativa — considerar cintilografia V/Q)',
    ],
    tempo: '20 – 40 min',
    obs: 'Aplicar escore de Wells antes de solicitar. D-dímero negativo exclui TEP em baixa probabilidade.',
  },
  {
    nome: 'Angio-TC de Crânio e Pescoço',
    grupo: 'Imagem — Tomografia Computadorizada',
    indicacoes: [
      'AVC isquêmico por oclusão de grande vaso (janela de trombectomia)',
      'Hemorragia subaracnóidea (pesquisa de aneurisma)',
      'Estenose de artéria carótida',
    ],
    preparo: [
      'Jejum de 4 h',
      'Verificar creatinina e alergia a contraste',
      'Acesso venoso calibroso',
    ],
    contraindicacoes: [
      'Alergia grave ao contraste iodado',
      'IRC grave',
      'Gravidez (relativa)',
    ],
    tempo: '20 – 40 min',
    obs: '',
  },

  // ── RESSONÂNCIA MAGNÉTICA ────────────────────────────────
  {
    nome: 'RM de Crânio (sem e com contraste)',
    grupo: 'Imagem — Ressonância Magnética',
    indicacoes: [
      'AVC isquêmico (DWI detecta isquemia em < 1 h)',
      'Esclerose múltipla',
      'Epilepsia (pesquisa de lesão estrutural)',
      'Neoplasia intracraniana',
      'Encefalite',
      'Demência de investigação',
    ],
    preparo: [
      'Remover TODOS os objetos metálicos (adornos, piercing, próteses removíveis)',
      'Triagem obrigatória de implantes (marca-passo, clipes aneurismáticos, parafusos)',
      'Investigar claustrofobia — considerar ansiolítico prescrito antecipadamente',
      'Com gadolínio: verificar função renal (TFG)',
    ],
    contraindicacoes: [
      'Marca-passo cardíaco (salvo dispositivos RM-compatíveis certificados)',
      'Clipes aneurismáticos metálicos antigos',
      'Corpo estranho metálico intraocular',
      'Claustrofobia grave (relativa — sedação pode ser necessária)',
    ],
    tempo: '30 – 60 min',
    obs: 'Superior à TC para fossa posterior, medula e isquemia aguda. Gadolínio contraindicado em TFG < 30.',
  },
  {
    nome: 'RM de Coluna Lombar',
    grupo: 'Imagem — Ressonância Magnética',
    indicacoes: [
      'Hérnia de disco lombar com radiculopatia',
      'Estenose do canal lombar',
      'Suspeita de tumor ou metástase vertebral',
      'Síndrome da cauda equina (urgência)',
    ],
    preparo: [
      'Remover objetos metálicos',
      'Triagem de implantes metálicos',
      'Investigar claustrofobia',
    ],
    contraindicacoes: [
      'Marca-passo (salvo RM-compatível)',
      'Implantes metálicos na coluna não certificados',
    ],
    tempo: '30 – 50 min',
    obs: 'Exame de escolha para discopatias, canalopatias e lesões medulares.',
  },
  {
    nome: 'RM de Coluna Cervical',
    grupo: 'Imagem — Ressonância Magnética',
    indicacoes: [
      'Mielopatia cervical',
      'Hérnia de disco cervical com radiculopatia',
      'Trauma cervical com suspeita de comprometimento medular',
      'Estenose do canal cervical',
    ],
    preparo: [
      'Remover objetos metálicos',
      'Triagem de implantes',
      'Investigar claustrofobia',
    ],
    contraindicacoes: ['Marca-passo (salvo RM-compatível)'],
    tempo: '30 – 50 min',
    obs: '',
  },
  {
    nome: 'RM de Joelho',
    grupo: 'Imagem — Ressonância Magnética',
    indicacoes: [
      'Lesão de menisco',
      'Ruptura de LCA ou LCP',
      'Condromalácia patelar',
      'Sinovite e derrame articular de investigação',
      'Dor no joelho sem diagnóstico ao Rx',
    ],
    preparo: [
      'Remover objetos metálicos',
      'Triagem de implantes',
    ],
    contraindicacoes: [
      'Prótese total de joelho (artefato significativo — avaliar TC)',
      'Marca-passo',
    ],
    tempo: '30 – 45 min',
    obs: '',
  },

  // ── ELETROFISIOLOGIA / FUNÇÃO CARDÍACA ───────────────────
  {
    nome: 'ECG em repouso (12 derivações)',
    grupo: 'Eletrofisiologia e Função Cardíaca',
    indicacoes: [
      'Dor torácica e suspeita de SCA',
      'Arritmias e palpitações',
      'Síncope',
      'Avaliação pré-operatória',
      'Monitorização de fármacos que prolongam QT',
      'HAS, IC, DM — rastreamento cardiovascular',
    ],
    preparo: [
      'Repouso de 5–10 min antes do exame',
      'Retirar adornos metálicos do tórax',
      'Pele limpa e seca nos locais dos eletrodos',
    ],
    contraindicacoes: [],
    tempo: '5 – 10 min',
    obs: 'Exame rápido e de baixo custo. Sempre comparar com ECG anterior quando disponível.',
  },
  {
    nome: 'Ecocardiograma transtorácico',
    grupo: 'Eletrofisiologia e Função Cardíaca',
    indicacoes: [
      'Avaliação de fração de ejeção em IC',
      'Sopro cardíaco e valvopatia',
      'Pericardite e derrame pericárdico',
      'Pós-IAM (função e complicações)',
      'Endocardite (triagem)',
    ],
    preparo: [
      'Jejum não necessário',
      'Retirar adornos metálicos do tórax',
      'Decúbito lateral esquerdo durante parte do exame',
    ],
    contraindicacoes: [],
    tempo: '30 – 60 min',
    obs: 'Operador-dependente. Janela acústica limitada em obesidade e DPOC.',
  },
  {
    nome: 'Holter 24 h',
    grupo: 'Eletrofisiologia e Função Cardíaca',
    indicacoes: [
      'Palpitações de investigação',
      'Síncope e pré-síncope',
      'Monitorização de arritmias',
      'Avaliação de eficácia de antiarrítmicos',
      'Bloqueios AV intermitentes',
    ],
    preparo: [
      'Manter atividades habituais durante as 24 h',
      'Anotar sintomas e horários exatos no diário fornecido',
      'Evitar banho com o equipamento',
      'Evitar campos eletromagnéticos intensos',
    ],
    contraindicacoes: [],
    tempo: '24 h de registro + análise',
    obs: 'Diário de sintomas do paciente é essencial para correlação dos achados.',
  },
  {
    nome: 'MAPA 24 h (Monitorização Ambulatorial da Pressão Arterial)',
    grupo: 'Eletrofisiologia e Função Cardíaca',
    indicacoes: [
      'Suspeita de hipertensão do jaleco branco',
      'Hipertensão mascarada',
      'Avaliação de eficácia de anti-hipertensivos',
      'HAS resistente',
      'Investigação de hipotensão postural',
    ],
    preparo: [
      'Manter atividades habituais durante o exame',
      'Manter o braço estendido e imóvel em cada medição',
      'Registrar sintomas, horários de sono e refeições no diário',
    ],
    contraindicacoes: [
      'Fibrilação atrial (exame menos confiável nessa arritmia)',
    ],
    tempo: '24 h de registro + análise',
    obs: 'Critério de HAS no MAPA: média de vigília ≥ 130/80 mmHg.',
  },

  // ── ENDOSCOPIA E PROCEDIMENTOS ───────────────────────────
  {
    nome: 'Endoscopia Digestiva Alta (EDA)',
    grupo: 'Endoscopia e Procedimentos',
    indicacoes: [
      'Hemorragia digestiva alta (hematêmese, melena)',
      'Disfagia ou odinofagia',
      'Epigastralgia persistente ou refratária',
      'Suspeita de úlcera péptica',
      'DRGE refratária a IBP',
      'Biópsia para H. pylori e neoplasia',
    ],
    preparo: [
      'Jejum de 8 h para sólidos e 4 h para líquidos claros',
      'Suspender anticoagulantes conforme protocolo EBSERH (habitualmente 5 dias antes)',
      'Informar alergias — especialmente lidocaína e benzodiazepínicos',
      'Acesso venoso periférico para sedação',
      'Acompanhante adulto obrigatório quando há sedação',
    ],
    contraindicacoes: [
      'Perfuração gastrointestinal suspeita ou confirmada',
      'IAM recente (< 3 meses) — relativa',
      'Instabilidade hemodinâmica grave não controlada',
      'Coagulopatia grave não corrigida (para procedimentos terapêuticos)',
    ],
    tempo: '15 – 30 min + recuperação da sedação (30–60 min)',
    obs: 'Consentimento informado obrigatório. Para pesquisa de H. pylori, suspender IBP 2 semanas e antibiótico 4 semanas antes.',
  },
  {
    nome: 'Colonoscopia',
    grupo: 'Endoscopia e Procedimentos',
    indicacoes: [
      'Rastreamento de câncer colorretal (≥ 50 anos ou risco aumentado)',
      'Hematoquezia e hemorragia digestiva baixa',
      'Diarreia crônica de investigação',
      'Seguimento de pólipos',
      'Doença inflamatória intestinal',
    ],
    preparo: [
      'Dieta sem resíduos 2 dias antes (sem frutas, verduras, grãos)',
      'Laxante intestinal na véspera — polietilenoglicol 4 L ou manitol (protocolo EBSERH)',
      'Jejum de 8 h no dia do exame',
      'Suspender AAS 5–7 dias, anticoagulantes e ferro oral conforme protocolo',
      'Acesso venoso para sedação',
      'Acompanhante adulto obrigatório',
    ],
    contraindicacoes: [
      'Perfuração intestinal',
      'Colite fulminante',
      'Instabilidade hemodinâmica',
      'IAM ou AVC recentes',
    ],
    tempo: '30 – 60 min + recuperação (30–60 min)',
    obs: 'Consentimento informado obrigatório. Resultado de biópsias em 7–15 dias úteis.',
  },
  {
    nome: 'Espirometria (com broncodilatador)',
    grupo: 'Endoscopia e Procedimentos',
    indicacoes: [
      'Diagnóstico de DPOC (VEF1/CVF pós-broncodilatador)',
      'Asma — reversibilidade com broncodilatador',
      'Avaliação pré-operatória de cirurgia torácica',
      'Monitorização de fibrose pulmonar e doenças intersticiais',
      'Dispneia de causa não determinada',
    ],
    preparo: [
      'Evitar SABA (broncodilatador de curta ação) 4 h antes',
      'Evitar LABA (broncodilatador de longa ação) 12 h antes',
      'Não fumar nas 4 h anteriores',
      'Refeição leve 2 h antes (refeição pesada prejudica a CVF)',
      'Trazer lista de medicamentos em uso',
    ],
    contraindicacoes: [
      'IAM recente (< 1 mês)',
      'Pneumotórax não drenado',
      'Hemoptise ativa',
      'Cirurgia ocular recente (elevação de pressão intraocular)',
      'Aneurisma de aorta ou cerebral (relativa)',
    ],
    tempo: '20 – 40 min',
    obs: 'Critério de obstrução: VEF1/CVF < 0,70 pós-BD (GOLD). Exige esforço máximo e cooperação — explique antes.',
  },
];

// Exportar para objeto global window
window.ExamesComplementaresDB = EXAMES_SOLICITADOS;
