const ORIENTACOES_ALTA = [
  {
    condicao: 'Hipertensão Arterial (HAS)',
    orientacoes: [
      'Manter dieta hipossódica (< 2 g de sal/dia)',
      'Evitar alimentos ultraprocessados, embutidos e enlatados',
      'Praticar atividade física regular conforme orientação médica (mínimo 150 min/semana de atividade moderada)',
      'Não interromper os medicamentos sem consultar o médico',
      'Monitorar a pressão arterial em casa, anotando os valores',
      'Evitar tabagismo e consumo excessivo de álcool',
      'Manter peso adequado (IMC < 25 kg/m²)',
      'Retornar em caso de cefaleia intensa, visão turva, dor torácica, dispneia ou PA > 180/110 mmHg',
    ],
    retorno: 'Retorno ambulatorial em 7–15 dias ou conforme agendamento da UBS',
  },
  {
    condicao: 'Diabetes Mellitus (DM)',
    orientacoes: [
      'Seguir dieta com baixo índice glicêmico: evitar açúcares simples, refrigerantes, doces e farinhas refinadas',
      'Preferir alimentos integrais, vegetais, leguminosas e proteínas magras',
      'Realizar glicemia capilar conforme orientação médica e anotar os resultados',
      'Não interromper insulina ou antidiabéticos orais sem orientação médica',
      'Inspecionar os pés diariamente (buscar feridas, bolhas, calosidades)',
      'Usar calçados adequados; evitar andar descalço',
      'Praticar atividade física regular (consultar médico antes de iniciar)',
      'Retornar imediatamente se: glicemia > 300 mg/dL, vômitos persistentes, sonolência ou confusão mental',
    ],
    retorno: 'Retorno em 15–30 dias para avaliação de controle glicêmico; HbA1c a cada 3 meses',
  },
  {
    condicao: 'Gastrite / DRGE',
    orientacoes: [
      'Evitar alimentos ácidos: tomate, laranja, limão, vinagre, café e bebidas carbonatadas',
      'Evitar alimentos gordurosos, fritos e condimentados',
      'Fazer refeições menores e mais frequentes (4–5 vezes ao dia)',
      'Não deitar imediatamente após as refeições; aguardar pelo menos 2 horas',
      'Elevar a cabeceira da cama 15–20 cm se houver pirose noturna',
      'Evitar tabagismo e álcool',
      'Tomar os medicamentos (IBP/antiácidos) conforme prescrito, geralmente 30 min antes das refeições',
      'Retornar se houver disfagia, vômitos com sangue, fezes escuras ou perda de peso não intencional',
    ],
    retorno: 'Retorno em 4–8 semanas; endoscopia se sintomas persistentes após 4–8 semanas de tratamento',
  },
  {
    condicao: 'Infecção do Trato Urinário (ITU)',
    orientacoes: [
      'Completar o ciclo completo do antibiótico prescrito, mesmo após melhora dos sintomas',
      'Aumentar a ingesta hídrica: pelo menos 2–3 litros de água por dia',
      'Urinar frequentemente; não segurar a urina por longos períodos',
      'Higiene íntima adequada: limpar sempre da frente para trás',
      'Evitar banhos de imersão e duchas vaginais',
      'Mulheres: urinar após relação sexual',
      'Evitar roupas íntimas sintéticas e muito justas',
      'Retornar se: febre persistente, dor lombar intensa, vômitos ou ausência de melhora em 48–72h',
    ],
    retorno: 'Retorno em 7 dias ou antes se piora; urocultura de controle após término do antibiótico (em gestantes e crianças)',
  },
  {
    condicao: 'Pneumonia Comunitária',
    orientacoes: [
      'Completar integralmente o antibiótico prescrito, mesmo após melhora clínica',
      'Repouso relativo; retornar às atividades gradualmente conforme melhora',
      'Manter boa hidratação: pelo menos 2 litros de água/dia',
      'Evitar tabagismo durante e após o tratamento',
      'Nebulização com SF 0,9% se prescrita; fisioterapia respiratória se indicada',
      'Monitorar saturação de O₂ em casa se disponível (retornar se SpO₂ < 94%)',
      'Vacinar-se contra influenza e pneumococo após recuperação',
      'Retornar imediatamente se: piora da dispneia, febre alta (> 39°C), confusão mental, SpO₂ < 94% ou cianose',
    ],
    retorno: 'Retorno em 48–72h para reavaliação clínica; radiografia de controle em 4–6 semanas',
  },
  {
    condicao: 'Dor Lombar Aguda (Lombalgia)',
    orientacoes: [
      'Evitar repouso absoluto no leito; manter-se ativo conforme tolerância à dor',
      'Aplicar compressas mornas na região lombar por 15–20 min, 3–4 vezes ao dia',
      'Tomar os analgésicos e anti-inflamatórios conforme prescrito; não ultrapassar a dose recomendada',
      'Evitar carregar peso excessivo e movimentos bruscos de rotação ou flexão do tronco',
      'Manter postura adequada ao sentar: coluna ereta, pés apoiados no chão',
      'Iniciar fisioterapia quando indicado pelo médico',
      'Exercícios de alongamento suave podem ser realizados conforme tolerância',
      'Retornar se: dor irradiada para as pernas (ciática), fraqueza nos membros inferiores, perda do controle de bexiga/intestino, febre ou trauma recente',
    ],
    retorno: 'Retorno em 7–14 dias; se sem melhora, avaliar fisioterapia e exames de imagem',
  },
  {
    condicao: 'Cefaleia / Enxaqueca',
    orientacoes: [
      'Identificar e evitar gatilhos pessoais: estresse, privação de sono, jejum prolongado, certos alimentos (queijo curado, embutidos, álcool, cafeína em excesso)',
      'Manter horários regulares de sono e alimentação',
      'Em caso de crise: repouso em ambiente escuro e silencioso; compressa fria na testa',
      'Tomar a medicação abortiva prescrita ao primeiro sinal de crise, não esperar a dor piorar',
      'Não abusar de analgésicos (máximo 2–3 dias/semana) para evitar cefaleia por uso excessivo',
      'Hidratação adequada; reduzir cafeína gradualmente se consumo excessivo',
      'Diário de cefaleia: anotar frequência, duração, intensidade e fatores desencadeantes',
      'Retornar imediatamente se: "pior dor de cabeça da vida", cefaleia com febre e rigidez de nuca, alteração visual súbita, fraqueza ou confusão mental',
    ],
    retorno: 'Retorno em 30 dias ou antes se crises muito frequentes (≥ 4/mês) — avaliar profilaxia',
  },
  {
    condicao: 'Crise Hipertensiva (Alta após estabilização)',
    orientacoes: [
      'Tomar RIGOROSAMENTE os medicamentos anti-hipertensivos prescritos nos horários corretos',
      'Não suspender o tratamento por conta própria, mesmo se sentir bem',
      'Monitorar a pressão arterial em casa, 2 vezes ao dia, anotar os valores',
      'Dieta com restrição de sal: evitar alimentos processados, embutidos e saleiros à mesa',
      'Evitar álcool, tabaco e estimulantes (café em excesso, energéticos)',
      'Controle do estresse: técnicas de relaxamento, atividade física regular',
      'Identificar fatores de descontrole: esquecimento de medicação, dieta inadequada, estresse intenso',
      'Retornar imediatamente se: PA > 180/110 mmHg, cefaleia intensa, dor torácica, dispneia, alteração visual ou neurológica',
    ],
    retorno: 'Retorno em 3–7 dias para reavaliação e ajuste da medicação conforme necessário',
  },
  {
    condicao: 'Diarreia Aguda / Gastroenterite',
    orientacoes: [
      'Hidratação oral rigorosa: soro de reidratação oral (SRO), água de coco, água com sal e açúcar',
      'Reintroduzir alimentação gradualmente: iniciar com alimentos leves (arroz, frango desfiado, banana, torrada)',
      'Evitar: laticínios, alimentos gordurosos, frituras, sucos cítricos e álcool por 48–72h',
      'Higienizar bem as mãos após usar o banheiro e antes de comer',
      'Se prescrito antibiótico, completar o ciclo completo',
      'Probióticos podem ser úteis conforme orientação médica',
      'Crianças e idosos: atenção redobrada à desidratação',
      'Retornar imediatamente se: febre alta, sangue ou muco nas fezes, diarreia por mais de 48–72h, sinais de desidratação grave (boca seca, olhos fundos, urina escura, confusão)',
    ],
    retorno: 'Retorno em 48–72h se não houver melhora; copro-urocultura se febre persistente',
  },
  {
    condicao: 'Asma / Broncoespasmo',
    orientacoes: [
      'Usar o broncodilatador de alívio (salbutamol/fenoterol) conforme prescrito nas crises; não usar em excesso',
      'Usar a medicação controladora (corticoide inalatório) DIARIAMENTE, mesmo sem sintomas',
      'Técnica correta do inalador: expirar antes, inspirar lenta e profundamente, segurar 10s',
      'Evitar desencadeantes: poeira, mofo, fumaça de cigarro, animais, perfumes fortes, ar muito frio',
      'Manter ambiente doméstico limpo: trocar fronhas e lençóis semanalmente, evitar tapetes e bichos de pelúcia',
      'Não fumar e evitar ambientes com fumaça',
      'Medir pico de fluxo expiratório (peak flow) conforme orientação médica',
      'Retornar imediatamente se: crise não melhora com broncodilatador após 3 doses em 1h, SpO₂ < 94%, fala em monossílabos, tiragem intercostal ou cianose',
    ],
    retorno: 'Retorno em 7–14 dias; reavaliação de controle da asma e técnica inalatória',
  },
];

// Exportar para objeto global window
window.OrientacoesDB = ORIENTACOES_ALTA;
